### ISSUE TITLE
installing problems

### ISSUE THREAD

**Issue by YanaSorina** [vincenzopronesti/MathematicalOptimization#1]
Hello, I found your realization of cutting stock algorithm and I'd like to test it on my computer. But I have a problem with starting. Could you help me?
![image](https://user-images.githubusercontent.com/40859894/112429438-b5fa2580-8d4d-11eb-9849-65326958fa38.png)

**Comment by vincenzopronesti** [comment]
Hi, I haven't used this code in a while so I'm a bit rusty. However, from what I remember, the directory ```toRun``` should contain some instances (input data) for the cutting stock problem. I'm not sure if I still have those files (I can check later). In the meantime, you can set 
```INSTANCE_PATH = "toRun/Waescher_TEST0058.txt"``` 
on line 14 in ```cutting_stock.py``` to 
```INSTANCE_PATH = None```
This way my code should use a random generator to create some fake input data. I think this should solve the issue. Let me know how it goes

**Comment by YanaSorina** [comment]
Hi, I noticed your answer. Actually I don't what I have done with this problem but thank you very much for your attention. I really appreciate it
